// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "clean/model"

// CustomerUseCase is an autogenerated mock type for the CustomerUseCase type
type CustomerUseCase struct {
	mock.Mock
}

// GetCustomerById provides a mock function with given fields: ctx, customerId
func (_m *CustomerUseCase) GetCustomerById(ctx context.Context, customerId int) (*model.Customer, error) {
	ret := _m.Called(ctx, customerId)

	var r0 *model.Customer
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.Customer); ok {
		r0 = rf(ctx, customerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, customerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
