// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "clean/model"

// EmailRepository is an autogenerated mock type for the EmailRepository type
type EmailRepository struct {
	mock.Mock
}

// GetEmailsByCustomerId provides a mock function with given fields: ctxt, customerId
func (_m *EmailRepository) GetEmailsByCustomerId(ctxt context.Context, customerId int) ([]*model.Email, error) {
	ret := _m.Called(ctxt, customerId)

	var r0 []*model.Email
	if rf, ok := ret.Get(0).(func(context.Context, int) []*model.Email); ok {
		r0 = rf(ctxt, customerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Email)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctxt, customerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
